---
- name: Configure VM and install required packages
  hosts: all
  become: yes

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install OpenJDK 17 JRE headless
      apt:
        name: openjdk-17-jre-headless
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Give permission to all users to run Docker commands
      command: chmod 666 /var/run/docker.sock

    - name: Pull SonarQube Docker image
      docker_image:
        name: mc1arke/sonarqube-with-community-branch-plugin
        source: pull

    - name: Run SonarQube container
      docker_container:
        name: sonar
        image: mc1arke/sonarqube-with-community-branch-plugin
        state: started
        ports:
          - "9000:9000"

    - name: Install Trivy
      snap:
        name: trivy
        state: latest